### ISSUE TITLE
Instrumentation breaks some AWS S3 requests

### ISSUE THREAD

**Issue by dobesv** [lightstep/otel-launcher-node#26]
**Describe the bug**

When we run the launcher in our project, some AWS S3 requests fail with this error:

```
SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

If we disable the instrumentation the error goes away.

**To Reproduce**

We run our application using this script as a pre-require script, then we try to access S3 buckets in the main script.

e.g. `node -r ./otel.js some-script-using-s3.js`

```
// otel.js
function getLogger() {
  return require('../../lib/server/logger/log').default.child({
    level: 'warn',
    subsystem: 'opentelemetry',
  });
}
if (process.env.LS_ACCESS_TOKEN) {
  require('lightstep-opentelemetry-launcher-node')
    .lightstep.configureOpenTelemetry({
      autoDetectResources: false,
      logger: getLogger(),
      serviceName:
        process.env.LS_SERVICE_NAME ||
        process.env.APM_SERVICE_NAME ||
        require('os')
          .hostname()
          .replace(/-[^-]+-[^-]+$/, ''),

      serviceVersion: process.env.APP_VERSION,
    })
    .start()
    .catch(err => getLogger().error(err));
}
```

My current guess is that it is adding headers to the AWS S3 requests, and that's breaking the signature calculation.

This issue doesn't seem to affect ALL S3 operations, but this piece of code was definitely failing:

```
const s3 = new AWS.S3();
  const objects = (await s3
    .listObjectsV2({ Bucket: bucket, ...(prefix && { Prefix: prefix }) })
    .promise()) as AWS.S3.Types.ListObjectsV2Output;
```

Probably will investigate a bit more and add more detail here later, but if anyone has run into a similar issue or has hints on how to prevent this, that might save us a lot of time.

**Comment by dobesv** [comment]
See also: https://stackoverflow.com/questions/64693442/wrong-aws-request-signature-caused-by-opentelemetry-https-plugin

**Comment by dobesv** [comment]
I haven't been able to reproduce this manually, I wonder if it only occurs in case of a retry as described in that StackOverflow post.

**Comment by dobesv** [comment]
This probably isn't an issue with this package, I'll find the appropriate place and file it there.

**Comment by TsvetanMilanov** [comment]
@dobesv a quick test with the [aws sdk v3](https://github.com/aws/aws-sdk-js-v3) showed that the issue with the retries and the `traceparent` header seems to be fixed.
I just wanted to share this as a possible solution to explore in case anyone else runs into this problem.
