### ISSUE TITLE
@opentelemetry/core 0.13.0 will not export the B3Propagator any more

### ISSUE THREAD

**Issue by dobesv** [lightstep/otel-launcher-node#28]
The launcher has to be updated to import from `@opentelemetry/propagator-b3`.

e.g. : https://github.com/lightstep/otel-launcher-node/blob/master/src/lightstep-opentelemetry-launcher-node.ts#L5

**Comment by mwear** [comment]
Closing as this has been addressed in the current launcher release: https://www.npmjs.com/package/lightstep-opentelemetry-launcher-node/v/0.13.0.
