### ISSUE TITLE
Update docs to explain if it is possible to use this launcher alongside accessory opentelemetry-js packages

### ISSUE THREAD

**Issue by hammadzz** [lightstep/otel-launcher-node#35]
**Is your feature request related to a problem? Please describe.**
I started using this to get quickly started with OpenTelemetry on LightStep. Now I wanted to add GraphQL Instrumentation from [@opentelemetry/instrumentation-graphql](https://www.npmjs.com/package/@opentelemetry/instrumentation-graphql). I cannot figure out if this sort of additional configuration is supported by this package. In this case it would be disabling 3 plugins (https, https, express) and running graphql instrumentation.

**Describe the solution you'd like**
Guidance of the limitations of this library. Is this more configurable or just a LightStep getting started package. 

In use case as mentioned above, should one use`@opentelemetry/node` package directly and configure it for LightStep export? If so how should it be configured to get the most out of LightStep (metrics, etc).

**Describe alternatives you've considered**
I ended up just adding the LightStep exporter to the example code provided for `@opentelemetry/instrumentation-graphql`. But setup of metrics from this library is missing in my code.

**Comment by dobesv** [comment]
Hi, if you really want the instrumentation all you have to do is "enable" it.  The documentation for the graphql instrumentation is a bit confusing on this point, though.

e.g.

```
    lightstep.configureOpenTelemetry({
        ... options ...
      })
      .start();
    new GraphQLInstrumentation({
      enabled: true,
      logger,
      mergeItems: true,
    });
```

It seems like for JavaScript the opentelemetry people are moving away from "plugins" (which you would configure in the `plugins` option to `configureOpenTelemtry` and towards these "instrumentations" which you just instantiate them with `enabled: true`.

**Comment by mwear** [comment]
Launcher is built around existing OpenTelemetry packages and simplifies configuration for use with Lightstep. It wraps the ` [@opentelemetry/sdk-node](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-sdk-node) package. All configuration options that are valid for the SDK Node package are valid for launcher. This is discussed briefly on the readme: https://github.com/lightstep/otel-launcher-node#additional-options. Please reopen if you need further clarification.
