### ISSUE TITLE
Add clarification on starting OTEL before any packages are loaded

### ISSUE THREAD

**Issue by hammadzz** [lightstep/otel-launcher-node#36]
**Is your feature request related to a problem? Please describe.**
On the LightStep blog post [here](https://lightstep.com/blog/opentelemetry-nodejs-express/) it states `OpenTelemetry must be started before any other packages are required.`. Yet the getting started on LightStep was instruction to run your code in the start callback. It may have missed to clarify the importance of using a startup script pattern as shown in the blog post.

**Describe the solution you'd like**
Update readme example to instruct on how to use a startup script to ensure OpenTelemetry is started before any other packages are loaded.

**Comment by dobesv** [comment]
What do you think of these proposed changes ?

https://github.com/lightstep/otel-launcher-node/pull/38

**Comment by mwear** [comment]
The docs were updated with @dobesv's suggestion in #41. I'm going to close this. Please reopen if you need further clarification.
