### ISSUE TITLE
`@opentelemetry/host-metrics` contains audit vulnerability 

### ISSUE THREAD

**Issue by JulesPatry** [lightstep/otel-launcher-node#43]
[Here](https://github.com/lightstep/otel-launcher-node/blob/master/package.json#L53), this lightstep package.json uses an old version of  `@opentelemetry/host-metrics` which has a dependency called `systeminformation`.  The `systeminformation`  dependency has a vulnerability with `npm audit`. To follow compliance agreements, our application cannot have this vulnerability.

More information on the systeminformation vulnerability 
— systeminformation is an open source system and OS information library for node.js. A command injection vulnerability has been discovered in versions of systeminformation prior to 5.6.4. The issue has been fixed with a parameter check on user input. Please upgrade to version >= 5.6.4. If you cannot upgrade, be sure to check or sanitize service parameters that are passed to si.inetLatency(), si.inetChecksite(), si.services(), si.processLoad() and other commands. Only allow strings, reject any arrays. String sanitation works as expected.

**To fix**
`"@opentelemetry/host-metrics": "^0.14.0",`  -> `"@opentelemetry/host-metrics": "^0.16.0",` 

**To Reproduce**
Simply run "npm audit" to see the vulnerabilities.

**Comment by obecny** [comment]
the upgrade which fixes this is here-> https://github.com/lightstep/otel-launcher-node/pull/42

**Comment by JulesPatry** [comment]
@obecny, awesome! Can you close this ticket when the PR is merged and the package is updated?

**Comment by JulesPatry** [comment]
Thanks @obecny
