### ISSUE TITLE
Update to opentelemetry 1.10

### ISSUE THREAD

**Issue by dobesv** [lightstep/otel-launcher-node#66]
We want some fixes in the latest opentelemetry releases but this has its dependencies locked to `~1.8.0`

It would be great if this could be released with compatible version ranges with the latest version.

**Comment by mwear** [comment]
We released v2.0 with updated dependencies yesterday: https://www.npmjs.com/package/lightstep-opentelemetry-launcher-node/v/2.0.0. Will this work for you? The reason for the major version bump is that the `start` method of the `NodeSDK` package is now synchronous. See the [updated example](https://github.com/lightstep/otel-launcher-node#setup-tracing) and [upgrade guide](https://github.com/lightstep/otel-launcher-node#upgrade-guidelines) for more details.

**Comment by dobesv** [comment]
Thanks, I'll try it out!
